"""SP65: one owner for "how is a gate launched" and "can the registered hooks
run at all" — a missing check is a blocker, never a skip."""
import importlib.util
import subprocess
import sys
from pathlib import Path


def _load(root: Path):
    path = root / "scripts/process/gate_invoke.py"
    spec = importlib.util.spec_from_file_location("gate_invoke", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _git(root: Path, *args: str):
    return subprocess.run(["git", *args], cwd=root, capture_output=True,
                          text=True, check=True)


def _repo(render, tmp_path, **mods):
    out = render(tmp_path, {"project_name": "demo",
                            "modules": {"git_hooks": True, **mods}})
    _git(out, "init", "-q", "-b", "main")
    _git(out, "config", "user.email", "t@example.com")
    _git(out, "config", "user.name", "Test")
    _git(out, "add", "-A")
    _git(out, "commit", "-q", "-m", "base")
    return out


def test_declared_dependencies_read_textually(render, tmp_path):
    out = render(tmp_path, {"project_name": "demo"})
    gi = _load(out)
    deps = gi.declared_dependencies(out / "scripts/process/gate_runner.py")
    assert any(d.lower().startswith("pyyaml") for d in deps), deps
    assert gi.declared_dependencies(out / "scripts/process/check_review.py") == []


def test_child_argv_routes_declaring_scripts_through_uv(render, tmp_path, monkeypatch):
    out = render(tmp_path, {"project_name": "demo"})
    gi = _load(out)
    monkeypatch.setattr(gi.shutil, "which", lambda name: "/usr/bin/uv")
    runner = ["python", "scripts/process/gate_runner.py", "--list"]
    assert gi.child_argv(out, runner)[:3] == ["uv", "run", "--script"]
    assert gi.child_argv(out, runner)[-1] == "--list"
    plain = ["python", "scripts/process/check_review.py", "."]
    assert gi.child_argv(out, plain) == plain  # no declaration: unchanged
    monkeypatch.setattr(gi.shutil, "which", lambda name: None)
    assert gi.child_argv(out, runner) == runner  # no uv: pre-existing behaviour


def test_gate_runner_argv_none_is_not_runnable_with_reason(render, tmp_path, monkeypatch):
    out = render(tmp_path, {"project_name": "demo"})
    gi = _load(out)
    monkeypatch.setattr(gi, "find_spec", lambda name: None)
    monkeypatch.setattr(gi.shutil, "which", lambda name: None)
    assert gi.gate_runner_argv(out) is None
    reason = gi.not_runnable_reason(out)
    assert "launch problem, not a gate finding" in reason
    monkeypatch.setattr(gi.shutil, "which", lambda name: "/usr/bin/uv")
    assert gi.gate_runner_argv(out)[:2] == ["uv", "run"]


def test_hook_doctor_silent_without_pre_commit_config(render, tmp_path):
    out = render(tmp_path, {"project_name": "demo"})
    _git(out, "init", "-q", "-b", "main")
    _git(out, "config", "core.hooksPath", ".githooks")
    gi = _load(out)
    assert gi.hook_wiring_findings(out) == ([], [])


def test_hook_doctor_hooks_path_makes_registrations_inert(render, tmp_path):
    out = _repo(render, tmp_path)
    gi = _load(out)
    hard, soft = gi.hook_wiring_findings(out)
    assert not hard and soft and "never installed" in soft[0]
    _git(out, "config", "core.hooksPath", ".githooks")
    hard, soft = gi.hook_wiring_findings(out)
    assert hard and "inert" in hard[0] and "one hook manager" in hard[0].lower()


def test_hook_doctor_sees_installed_pre_commit(render, tmp_path):
    out = _repo(render, tmp_path)
    hooks = Path(_git(out, "rev-parse", "--git-path", "hooks").stdout.strip())
    hooks = hooks if hooks.is_absolute() else out / hooks
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-push").write_text("#!/bin/sh\n# File generated by pre-commit\n")
    gi = _load(out)
    assert gi.hook_wiring_findings(out) == ([], [])


def test_gate_runner_fails_hook_wiring_not_silently(render, tmp_path):
    out = _repo(render, tmp_path)
    _git(out, "config", "core.hooksPath", ".githooks")
    r = subprocess.run([sys.executable, "scripts/process/gate_runner.py"],
                       cwd=out, capture_output=True, text=True)
    assert r.returncode == 1
    assert "hook-wiring" in r.stderr and "hook-wiring" in r.stdout


def test_finish_blocks_on_inert_hooks(render, tmp_path):
    out = _repo(render, tmp_path)
    _git(out, "checkout", "-q", "-b", "feature")
    _git(out, "config", "core.hooksPath", ".githooks")
    r = subprocess.run([sys.executable, "scripts/process/finish.py", "."],
                       cwd=out, capture_output=True, text=True)
    assert r.returncode == 1
    assert "hooks:" in r.stdout and "inert" in r.stdout


def test_hook_doctor_tracked_githooks_need_hooks_path(render, tmp_path):
    # a tracked .githooks/ that core.hooksPath does not point at is never
    # read by git — a stale .git/hooks copy (or nothing) runs instead
    out = render(tmp_path, {"project_name": "demo"})
    _git(out, "init", "-q", "-b", "main")
    (out / ".githooks").mkdir()
    (out / ".githooks" / "pre-push").write_text("#!/bin/sh\nexit 0\n")
    gi = _load(out)
    hard, _soft = gi.hook_wiring_findings(out)
    assert hard and "core.hooksPath is unset" in hard[0]
    _git(out, "config", "core.hooksPath", ".githooks")
    assert gi.hook_wiring_findings(out) == ([], [])
