"""SP65: one owner for "how is a gate launched" and "can the registered hooks
run at all" — a missing check is a blocker, never a skip."""
import importlib.util
import subprocess
import sys
from pathlib import Path


def _load(root: Path):
    path = root / "scripts/process/gate_invoke.py"
    spec = importlib.util.spec_from_file_location("gate_invoke", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _git(root: Path, *args: str):
    return subprocess.run(["git", *args], cwd=root, capture_output=True,
                          text=True, check=True)


def _repo(render, tmp_path, **mods):
    out = render(tmp_path, {"project_name": "demo",
                            "modules": {"git_hooks": True, **mods}})
    _git(out, "init", "-q", "-b", "main")
    _git(out, "config", "user.email", "t@example.com")
    _git(out, "config", "user.name", "Test")
    _git(out, "add", "-A")
    _git(out, "commit", "-q", "-m", "base")
    return out


def test_declared_dependencies_read_textually(render, tmp_path):
    out = render(tmp_path, {"project_name": "demo"})
    gi = _load(out)
    deps = gi.declared_dependencies(out / "scripts/process/gate_runner.py")
    assert any(d.lower().startswith("pyyaml") for d in deps), deps
    assert gi.declared_dependencies(out / "scripts/process/check_review.py") == []


def test_child_argv_routes_declaring_scripts_through_uv(render, tmp_path, monkeypatch):
    out = render(tmp_path, {"project_name": "demo"})
    gi = _load(out)
    monkeypatch.setattr(gi.shutil, "which", lambda name: "/usr/bin/uv")
    runner = ["python", "scripts/process/gate_runner.py", "--list"]
    assert gi.child_argv(out, runner)[:3] == ["uv", "run", "--script"]
    assert gi.child_argv(out, runner)[-1] == "--list"
    plain = ["python", "scripts/process/check_review.py", "."]
    assert gi.child_argv(out, plain) == plain  # no declaration: unchanged
    monkeypatch.setattr(gi.shutil, "which", lambda name: None)
    assert gi.child_argv(out, runner) == runner  # no uv: pre-existing behaviour


def test_gate_runner_argv_none_is_not_runnable_with_reason(render, tmp_path, monkeypatch):
    out = render(tmp_path, {"project_name": "demo"})
    gi = _load(out)
    monkeypatch.setattr(gi, "find_spec", lambda name: None)
    monkeypatch.setattr(gi.shutil, "which", lambda name: None)
    assert gi.gate_runner_argv(out) is None
    reason = gi.not_runnable_reason(out)
    assert "launch problem, not a gate finding" in reason
    monkeypatch.setattr(gi.shutil, "which", lambda name: "/usr/bin/uv")
    assert gi.gate_runner_argv(out)[:2] == ["uv", "run"]


def test_hook_doctor_silent_without_pre_commit_config(render, tmp_path):
    out = render(tmp_path, {"project_name": "demo"})
    _git(out, "init", "-q", "-b", "main")
    _git(out, "config", "core.hooksPath", ".githooks")
    gi = _load(out)
    assert gi.hook_wiring_findings(out) == ([], [])


def test_hook_doctor_hooks_path_makes_registrations_inert(render, tmp_path):
    out = _repo(render, tmp_path)
    gi = _load(out)
    hard, soft = gi.hook_wiring_findings(out)
    assert not hard and soft and "never installed" in soft[0]
    _git(out, "config", "core.hooksPath", ".githooks")
    hard, soft = gi.hook_wiring_findings(out)
    assert hard and "inert" in hard[0] and "one hook manager" in hard[0].lower()


def test_hook_doctor_sees_installed_pre_commit(render, tmp_path):
    out = _repo(render, tmp_path)
    hooks = Path(_git(out, "rev-parse", "--git-path", "hooks").stdout.strip())
    hooks = hooks if hooks.is_absolute() else out / hooks
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-push").write_text("#!/bin/sh\n# File generated by pre-commit\n")
    gi = _load(out)
    # pre-commit's hook without the merge guard in front of it: a note, not a
    # blocker — `merge_route --hook-check` already refuses a push to main the guard
    # did not see; a hard finding here refused every BRANCH push of a clone that
    # updated without running the installer (refute round 2, F4)
    hard, soft = gi.hook_wiring_findings(out)
    assert not hard and any("install_hooks.py" in s for s in soft), (hard, soft)
    r = subprocess.run([sys.executable, "scripts/process/install_hooks.py"], cwd=out,
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    assert (hooks / "pre-push.legacy").is_file()
    assert gi.hook_wiring_findings(out) == ([], [])


def test_hook_doctor_expects_no_guard_without_the_module(render, tmp_path):
    # a project's own pre-commit config, no git-hooks module: no guard shipped
    out = render(tmp_path, {"project_name": "demo"})
    _git(out, "init", "-q", "-b", "main")
    (out / ".pre-commit-config.yaml").write_text("repos: []\n")
    hooks = out / ".git/hooks"
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-push").write_text("#!/bin/sh\n# File generated by pre-commit\n")
    assert _load(out).hook_wiring_findings(out) == ([], [])


def test_hook_doctor_guard_alone_is_no_installed_framework(render, tmp_path):
    # the guard installed before pre-commit sits at pre-push: still "never installed"
    out = _repo(render, tmp_path)
    r = subprocess.run([sys.executable, "scripts/process/install_hooks.py"], cwd=out,
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    hard, soft = _load(out).hook_wiring_findings(out)
    assert not hard and soft and "never installed" in soft[0]


def test_gate_runner_fails_hook_wiring_not_silently(render, tmp_path):
    out = _repo(render, tmp_path)
    _git(out, "config", "core.hooksPath", ".githooks")
    r = subprocess.run([sys.executable, "scripts/process/gate_runner.py"],
                       cwd=out, capture_output=True, text=True)
    assert r.returncode == 1
    assert "hook-wiring" in r.stderr and "hook-wiring" in r.stdout


def test_finish_blocks_on_inert_hooks(render, tmp_path):
    out = _repo(render, tmp_path)
    _git(out, "checkout", "-q", "-b", "feature")
    _git(out, "config", "core.hooksPath", ".githooks")
    r = subprocess.run([sys.executable, "scripts/process/finish.py", "."],
                       cwd=out, capture_output=True, text=True)
    assert r.returncode == 1
    assert "hooks:" in r.stdout and "inert" in r.stdout


def test_hook_doctor_tracked_githooks_need_hooks_path(render, tmp_path):
    # a tracked .githooks/ that core.hooksPath does not point at is never
    # read by git — a stale .git/hooks copy (or nothing) runs instead
    out = render(tmp_path, {"project_name": "demo"})
    _git(out, "init", "-q", "-b", "main")
    (out / ".githooks").mkdir()
    (out / ".githooks" / "pre-push").write_text("#!/bin/sh\nexit 0\n")
    gi = _load(out)
    hard, _soft = gi.hook_wiring_findings(out)
    assert hard and "core.hooksPath is unset" in hard[0]
    _git(out, "config", "core.hooksPath", ".githooks")
    assert gi.hook_wiring_findings(out) == ([], [])


def test_hook_doctor_stays_quiet_in_ci(render, tmp_path, monkeypatch):
    # a CI checkout installs no local hooks and needs none: the job is the gate
    out = _repo(render, tmp_path)
    _git(out, "config", "core.hooksPath", ".githooks")
    gi = _load(out)
    assert gi.hook_wiring_findings(out)[0]
    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    assert gi.hook_wiring_findings(out) == ([], [])


# --- #134: the repair hint names the installer the project has ---


def _githooks_project(render, tmp_path, installer: str | None):
    out = _repo(render, tmp_path, git_hooks=False)  # no install_hooks.py, no pre-commit config
    (out / ".githooks").mkdir()
    (out / ".githooks/pre-push").write_text("#!/bin/sh\nexit 0\n")
    if installer == "script":
        (out / "scripts/install_hooks.sh").write_text("#!/bin/sh\ngit config core.hooksPath .githooks\n")
    elif installer == "make":
        (out / "Makefile").write_text("hooks:\n\tgit config core.hooksPath .githooks\n")
    return out


def test_tracked_hooks_hint_names_the_projects_installer(render, tmp_path):
    out = _githooks_project(render, tmp_path, "script")

    hard, _soft = _load(out).hook_wiring_findings(out)

    assert hard and "scripts/install_hooks.sh" in hard[0], hard


def test_tracked_hooks_hint_names_a_make_target(render, tmp_path):
    out = _githooks_project(render, tmp_path, "make")

    hard, _soft = _load(out).hook_wiring_findings(out)

    assert hard and "make hooks" in hard[0], hard


def test_tracked_hooks_without_an_installer_get_the_git_config_line(render, tmp_path):
    out = _githooks_project(render, tmp_path, None)

    hard, _soft = _load(out).hook_wiring_findings(out)

    assert hard and "git config core.hooksPath .githooks" in hard[0], hard


def test_no_hint_names_an_installer_the_project_does_not_have(render, tmp_path):
    """Downstream refute: a project with its own .githooks (no git-hooks module) was told
    to run `scripts/process/install_hooks.py`, which it does not have."""
    out = _githooks_project(render, tmp_path, "script")
    _git(out, "config", "core.hooksPath", ".githooks")
    (out / ".pre-commit-config.yaml").write_text("repos: []\n")

    hard, soft = _load(out).hook_wiring_findings(out)

    assert hard and not any("install_hooks.py" in f for f in hard + soft), (hard, soft)
