"""gen_sbom — generate this repository's SBOM from pyproject.toml and uv.lock.

Writes two files, both derived, never hand-edited:

    docs/SBOM.md        human-readable (German, like the rest of docs/)
    docs/sbom.cdx.json  CycloneDX 1.5 JSON for tools (Dependency-Track & co.)

The output is deterministic: no timestamps, sorted components, the version
comes from pyproject.toml. That makes a drift check possible:

    python3 tools/gen_sbom.py           # regenerate
    python3 tools/gen_sbom.py --check   # exit 1 when a file is stale

tests/test_sbom.py runs the check in CI, so a change to pyproject.toml or
uv.lock without a regenerated SBOM cannot merge. Stdlib only (Python 3.11+).
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MD = ROOT / "docs" / "SBOM.md"
CDX = ROOT / "docs" / "sbom.cdx.json"

# Material vendored in the template (not a Python package); source of truth
# for the wording is THIRD-PARTY-NOTICES.md.
VENDORED = [
    {
        "name": "spec-kit spec-template (derivative)",
        "path": "template/{% if modules.speckit %}.specify{% endif %}/templates/overrides/spec-template.md",
        "license": "MIT",
        "origin": "https://github.com/github/spec-kit",
    },
    {
        "name": "spec-kit tasks-template (derivative)",
        "path": "template/{% if modules.speckit %}.specify{% endif %}/templates/overrides/tasks-template.md",
        "license": "MIT",
        "origin": "https://github.com/github/spec-kit",
    },
]

TOOLS = [
    ("`git`", "Template-Quelle klonen, Updates, lokale Hooks",
     "erforderlich"),
    ("`uv`", "portable Python-Laufzeit und isolierte Gate-Abhängigkeiten", "erforderlich"),
    ("`gh`", "Existenzprüfung im `github-issues`-Modul, Tempo-Familie des KPI-Cockpits",
     "optional"),
    ("`specify-cli`", "Spec-Kit-Setup im Zielrepo (gepinnte Version, siehe Modul-Doku)",
     "optional, Standard-Setup"),
    ("`tmux`", "sichtbare Worker-Fenster beim Runner `tmux`", "optional"),
    ("`import-linter` / `dependency-cruiser`", "best-effort Architektur-Layering im Zielrepo",
     "optional"),
]


def _norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def load() -> dict:
    py = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = py["project"]
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    direct: dict[str, str] = {}
    for group in py.get("dependency-groups", {}).values():
        for spec in group:
            m = re.match(r"\s*([A-Za-z0-9_.\-]+)\s*(.*)", spec)
            direct[_norm(m.group(1))] = m.group(2).strip() or "-"
    for spec in project.get("dependencies", []):
        m = re.match(r"\s*([A-Za-z0-9_.\-]+)\s*(.*)", spec)
        direct[_norm(m.group(1))] = m.group(2).strip() or "-"
    pkgs = []
    for p in lock.get("package", []):
        if "virtual" in p.get("source", {}) or _norm(p["name"]) == _norm(project["name"]):
            continue
        deps = []
        for d in p.get("dependencies", []):
            deps.append((_norm(d["name"]), d.get("marker", "")))
        sdist = p.get("sdist", {})
        pkgs.append({
            "name": _norm(p["name"]),
            "version": p["version"],
            "registry": p.get("source", {}).get("registry", ""),
            "deps": sorted(deps),
            "sha256": sdist.get("hash", "").removeprefix("sha256:"),
            "url": sdist.get("url", ""),
        })
    pkgs.sort(key=lambda x: x["name"])
    return {"project": project, "direct": direct, "packages": pkgs}


def render_md(data: dict) -> str:
    proj = data["project"]
    lines = [
        "# Software Bill of Materials",
        "",
        "<!-- generated by tools/gen_sbom.py — do not edit by hand -->",
        "",
        f"Stand: `dev-process` `{proj['version']}`. Diese Datei und "
        "[`sbom.cdx.json`](sbom.cdx.json) (CycloneDX 1.5, maschinenlesbar) werden von "
        "`tools/gen_sbom.py` aus `pyproject.toml` und `uv.lock` erzeugt; ein Test "
        "schlägt fehl, sobald sie veraltet sind.",
        "",
        "Das Repository ist ein copier-Template. Es liefert keinen Laufzeitcode als "
        "Paket aus; die Python-Pakete unten braucht nur, wer das Template selbst "
        "entwickelt oder testet. Die gerenderten Gate-Skripte laufen mit der "
        "Python-Standardbibliothek und PyYAML (PEP-723-Metadaten, von `uv` "
        "bereitgestellt).",
        "",
        "## Projekt",
        "",
        "| Komponente | Version | Lizenz |",
        "|---|---:|---|",
        f"| `{proj['name']}` | `{proj['version']}` | {proj.get('license', '-')} |",
        "",
        "## Direkte Python-Abhängigkeiten (Entwicklung)",
        "",
        "| Paket | Constraint |",
        "|---|---|",
    ]
    for name in sorted(data["direct"]):
        lines.append(f"| `{name}` | `{data['direct'][name]}` |")
    lines += [
        "",
        "## Aufgelöste Python-Pakete",
        "",
        "Alle aus `https://pypi.org/simple`. Abhängigkeiten mit Plattform- oder "
        "Versionsbedingung sind mit * markiert.",
        "",
        "| Paket | Version | Direkt | Abhängigkeiten |",
        "|---|---:|:---:|---|",
    ]
    for p in data["packages"]:
        deps = ", ".join(f"`{n}`" + ("*" if mk else "") for n, mk in p["deps"]) or "-"
        d = "ja" if p["name"] in data["direct"] else "nein"
        lines.append(f"| `{p['name']}` | `{p['version']}` | {d} | {deps} |")
    lines += [
        "",
        "## Eingebettetes Fremdmaterial",
        "",
        "| Datei im Template | Herkunft | Lizenz |",
        "|---|---|---|",
    ]
    for v in VENDORED:
        lines.append(f"| {v['name']} | {v['origin']} | {v['license']} |")
    lines += [
        "",
        "Details: [`THIRD-PARTY-NOTICES.md`](../THIRD-PARTY-NOTICES.md).",
        "",
        "## Externe Werkzeuge (keine Pakete dieses Repositorys)",
        "",
        "| Werkzeug | Wann relevant | Status |",
        "|---|---|---|",
    ]
    for t in TOOLS:
        lines.append(f"| {t[0]} | {t[1]} | {t[2]} |")
    lines += [
        "",
        "## Pflege",
        "",
        "Nach jeder Änderung an `pyproject.toml` oder `uv.lock`:",
        "",
        "    python3 tools/gen_sbom.py",
        "",
    ]
    return "\n".join(lines)


def _purl(p: dict) -> str:
    return f"pkg:pypi/{p['name']}@{p['version']}"


def render_cdx(data: dict) -> str:
    proj = data["project"]
    root_ref = f"pkg:github/Crashman1983/dev-process@{proj['version']}"
    comps = []
    for p in data["packages"]:
        c = {
            "type": "library",
            "bom-ref": _purl(p),
            "name": p["name"],
            "version": p["version"],
            "purl": _purl(p),
            "scope": "optional",
        }
        if p["sha256"]:
            c["hashes"] = [{"alg": "SHA-256", "content": p["sha256"]}]
        if p["url"]:
            c["externalReferences"] = [{"type": "distribution", "url": p["url"]}]
        comps.append(c)
    for v in VENDORED:
        comps.append({
            "type": "file",
            "bom-ref": f"file:{v['path']}",
            "name": v["name"],
            "licenses": [{"license": {"id": v["license"]}}],
            "externalReferences": [{"type": "vcs", "url": v["origin"]}],
        })
    versions = {p["name"]: p["version"] for p in data["packages"]}
    deps = [{
        "ref": root_ref,
        "dependsOn": sorted(f"pkg:pypi/{n}@{versions[n]}" for n in data["direct"] if n in versions),
    }]
    for p in data["packages"]:
        deps.append({
            "ref": _purl(p),
            "dependsOn": sorted({f"pkg:pypi/{n}@{versions[n]}" for n, _ in p["deps"] if n in versions}),
        })
    bom = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        # deterministic serial: derived from the project version and the lock content
        "serialNumber": "urn:uuid:" + str(uuid.uuid5(
            uuid.NAMESPACE_URL,
            root_ref + "|" + "|".join(_purl(p) for p in data["packages"]))),
        "version": 1,
        "metadata": {
            "tools": {"components": [{"type": "application", "name": "tools/gen_sbom.py"}]},
            "component": {
                "type": "application",
                "bom-ref": root_ref,
                "name": proj["name"],
                "version": proj["version"],
                "description": proj.get("description", ""),
                "licenses": [{"license": {"id": proj.get("license", "NOASSERTION")}}],
                "purl": root_ref,
            },
        },
        "components": comps,
        "dependencies": deps,
    }
    return json.dumps(bom, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    data = load()
    outputs = {MD: render_md(data), CDX: render_cdx(data)}
    if "--check" in argv:
        stale = [p for p, text in outputs.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        for p in stale:
            print(f"gen_sbom: {p.relative_to(ROOT)} is stale — run `python3 tools/gen_sbom.py`",
                  file=sys.stderr)
        return 1 if stale else 0
    for p, text in outputs.items():
        p.write_text(text, encoding="utf-8", newline="\n")
        print(f"gen_sbom: wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
